### ISSUE TITLE
FR : PolyX number of Channels Select

### ISSUE THREAD

**Issue by Petervos2018** [Coirt/Bark#25]
Hi Phil, as it is now it does not matter how many channels are connected to polyX 
it always outputs 16.
Problem is that this is CPU expensive in some cases , see pic  below. (CPU Bleak !)

![BarkPolyX30102019](https://user-images.githubusercontent.com/46076474/67856211-4c53f880-fb14-11e9-9151-04d698cf7465.png)

Is there a way you can make it that the number of channels is selectable or automatic (like in Merge).

Greetings Peter.

**Comment by Coirt** [comment]
Hi Peter, I was going to add this menu option at the start but decided not to as PolyX is designed for PolyMix. It was a design decision in particular when sending to level and pan on PolyMix the open (level mod) / closed (centre pan) state of the signal would neglect auto channels but if you set to say 2 channels in the menu the other open/closed buttons will stop functioning also when set to auto the input ports need to be connected in order to be activated which would also stop the buttons injecting voltage into the signal. 

You probably already know this but Bleak is picking up 8 channels from Merge it is the nature of auto channels. The way Auto channelling is working in the screenshot is not sending 3 channels from merge, as indicated by Viz but sending 8, for auto channels it is the amount of connections to the ports but also the order of connections. So connecting to 1 and 16 with everything else disconnected is still sending 16 channels whereas connecting to 1, 2 and 3 would send 3 channels.

I'll look into adding the menu option!

**Comment by Petervos2018** [comment]
Hi Phil,
Thanks for replying.
>PolyX is designed for PolyMix.

I thought so, but I don't use it that way ;)

> I'll look into adding the menu option!

Cool!

Thanks Peter.

**Comment by Coirt** [comment]
Hi @Petervos2018 have been very busy over the last few months. Just got around to adding this FR. It will be available in an upcoming release v1.2.0

**Comment by Petervos2018** [comment]
Thanks for this, although the automatic function does not work, on W10 when I connect just 1 input it still gives me 16 active outputs/channels. But the choose number of channels works.

Greetings Peter.

**Comment by Coirt** [comment]
That's because Auto detects the Voltage of 0v from the mute buttons instead of the condition of having a cable connected, as said before I didn't add the context menu because of this condition with Auto channels, It will break the module if set to auto and connected but no cable on the level or pan mods on Poly Mix. I can rename the menu item to "All".

**Comment by Petervos2018** [comment]
I thought as much but don't change it just for me, I'm glad with the channel choice as is 👍 
And the red and green lights 🥇 
And what's in a name.... although I think "All" is more appropriate. 

Thanks  and greetings,
Peter.

**Comment by Coirt** [comment]
No worries thanks for the feedback and the requests! I'll put it on the TODO list, it's a very minor change so I'll get it next update!
